{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 선형대수 정리\n",
    "##    1. 선형변환\n",
    "##    2. 고유값 고유벡터\n",
    "\n",
    "# 1. 선형 변환\n",
    "선형변환? : 벡터에 행렬을 곱해 또 다른 벡터를 만드는 함수. , 하나의 벡터 공간에 또 다른 벡터 공간으로, 벡터의 특징을 유지한 채 변환하는 방법.\n",
    "### 식1\n",
    "A = \n",
    "$ \\begin{bmatrix}\n",
    "-1 & 2 \\\\\n",
    "1 & 1\n",
    "\\end{bmatrix}$\n",
    "  b = $ \\begin{bmatrix}\n",
    "3 \\\\\n",
    "2\n",
    "\\end{bmatrix}$\n",
    "\n",
    "Ab = \n",
    "$ \\begin{bmatrix}\n",
    "1 \\\\\n",
    "5\n",
    "\\end{bmatrix}$\n",
    "\n",
    "### 식2\n",
    "b의 표준기저 e 를 구하면\n",
    "b = 3 $ \\begin{bmatrix}\n",
    "1 \\\\\n",
    "0\n",
    "\\end{bmatrix}$ + \n",
    "2$ \\begin{bmatrix}\n",
    "0 \\\\\n",
    "1\n",
    "\\end{bmatrix}$\n",
    "= 3e.x + 2e.y\n",
    "\n",
    "표준기저 e 를 이용해서 Ab구하기\n",
    "표준기저란? X축 Y축 z축 처럼 일종의 '좌표계'를 정할 수 있는 벡터집합\n",
    "b의 표준기저 : \n",
    "e.x = $ \\begin{bmatrix}\n",
    "1 \\\\\n",
    "0\n",
    "\\end{bmatrix}$\n",
    "e.y = $ \\begin{bmatrix}\n",
    "0 \\\\\n",
    "1\n",
    "\\end{bmatrix}$\n",
    "\n",
    "\n",
    "\n",
    "### 식3\n",
    "A를 두개의 열벡터로 나누면 \n",
    "e1 = $ \\begin{bmatrix}\n",
    "-1 \\\\\n",
    "1\n",
    "\\end{bmatrix}$\n",
    "e2 = $ \\begin{bmatrix}\n",
    "2 \\\\\n",
    "1\n",
    "\\end{bmatrix}$\n",
    "\n",
    "\n",
    "Ab = $ \\begin{bmatrix}\n",
    "\n",
    "-1 & 2 \\\\\n",
    "1 & 1\n",
    "\\end{bmatrix}$\n",
    "{3$ \\begin{bmatrix}\n",
    "1 \\\\\n",
    "0\n",
    "\\end{bmatrix}$\n",
    "+\n",
    "2$ \\begin{bmatrix}\n",
    "0 \\\\\n",
    "1\n",
    "\\end{bmatrix}$}\n",
    "\n",
    "\n",
    "2x2 2x1 행렬곱 생략\n",
    "\n",
    "= 3$ \\begin{bmatrix}\n",
    "-1 \\\\\n",
    "1\n",
    "\\end{bmatrix}$\n",
    "+\n",
    "2$ \\begin{bmatrix}\n",
    "2 \\\\\n",
    "1\n",
    "\\end{bmatrix}$\n",
    "=3e1 + 2e2 = $ \\begin{bmatrix}\n",
    "1 \\\\\n",
    "5\n",
    "\\end{bmatrix}$\n",
    "\n",
    "### 수학적 의미\n",
    "### 식2의 의미 : e.x방향으로 3만큼 e.y방향으로 2만큼 움직인 지점\n",
    "\n",
    "### 식3의 의미 : 식2와 같은 방법으로 e1의 3만큼 e2의 2만큼 움직인 지점 은 같은 스칼라배로 움직였다는 것을 알 수 있다.  이에 따라 행렬의 계산은 벡터를 회전하거나 확대, 또는 축소시킨 것과 같은 효과를 나타냄\n",
    "\n",
    "### 결론 선형 변환이라는 말은 어떤 벡터값에 행렬A를 곱한다는 것은 그 벡터를 다른 벡터공간으로 변환하고자회전,확대, 축소 한다는 것과 같음\n",
    "\n",
    "\n",
    "# 2. 고유값과 고유벡터\n",
    "\n",
    "### 고윳값 : 어떤 데이터가 가진 특징을 얼마나 잘 설명할 수 있는지 가늠할때 \n",
    "\n",
    "### 기여율 : 주성분, 고유벡터에 대응하는 고윳값을 전체 고윳값들의 총합으로 나눈 것, 주성분이 우리가 가진 데이터를 얼마나 잘 설명할 수 있는지 평가 하는 척도로 사용.\n",
    "\n",
    "#### 편의를 위해 n  = 람다기호\n",
    "####  n =  교유값 x = 고유벡터(단 x는 0이 아니다)\n",
    "#### $ Ax = nEx $\n",
    "\n",
    "#### $(A-nE)x = 0 $\n",
    "\n",
    "### 1. 고유벡터가 존재하려면고유방정식인 det(A-nE) = 0 이어야 한다\n",
    "### 2. 보통 행렬을 선형변환 하면 벡터의 방향이 변하기 마련인데 고유벡터같은 경우에는 방향은 변하지 않거나, 역방향이 된다. 변환 전과 후의 비율을 교윳값이라고 한다. \n",
    "### 3. 벡터의 길이 비율 : 고윳값,  벡터 방향 : 고유벡터\n",
    "### EX) 고유벡터와 고유값을 찾기\n",
    "### $ \\begin{bmatrix}\n",
    "2 & 4 \\\\\n",
    "-1 & -3 \n",
    "\\end{bmatrix}$ 고유값 존재 확인\n",
    "### det($ \\begin{bmatrix}\n",
    "2 & 4 \\\\\n",
    "-1 & -3 \n",
    "\\end{bmatrix}$ -n $ \\begin{bmatrix}\n",
    "1 & 0 \\\\\n",
    "0 & 1 \n",
    "\\end{bmatrix}$ ) = 0\n",
    "### det($ \\begin{bmatrix}\n",
    "2-n & 4 \\\\\n",
    "-1 & -3-n \n",
    "\\end{bmatrix}$ )\n",
    "\n",
    "### 행렬식 : ad-bd  \n",
    "### $ (2-n)(-3-n) * -4(-1)  = 0 $\n",
    "### $ n^2 + n -2  = 0$\n",
    "### $ (n+2)(n-1) = 0 $\n",
    "### 고유값 n 은 -2 or 1\n",
    "## n = -2 일때 고유벡터 구하기\n",
    "### (A-(-2)E)x = 0\n",
    "### A값과 E를 삽입해 x를 구한다 구하는 식 생략\n",
    "### $ \\begin{bmatrix}\n",
    "4 & 4 \\\\\n",
    "-1 & -1 \n",
    "\\end{bmatrix}$ x = 0 \n",
    "### $ \\begin{bmatrix}\n",
    "4 & 4 \\\\\n",
    "-1 & -1 \n",
    "\\end{bmatrix}$ $ \\begin{bmatrix}\n",
    "a \\\\\n",
    "b \n",
    "\\end{bmatrix}$ = 0\n",
    "$ a+b = 0 $\n",
    "### a를 임의의 상수 t로 두면 b는 -t\n",
    "### 즉  x는 $ \\begin{bmatrix}\n",
    "1 \\\\\n",
    "-1 \n",
    "\\end{bmatrix}$ 상수배이다.\n",
    "\n",
    "## n = 1 일때 a= -4b\n",
    "### a가 임의의 상수 t일때 b는 = -1/4t\n",
    "### x는 $ \\begin{bmatrix}\n",
    "4\\\\\n",
    "-1 \n",
    "\\end{bmatrix}$ 의 상수배이다.\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 확률과 통계\n",
    "\n",
    "## 1. 확률변수와 확률분포\n",
    "\n",
    "\n",
    "## 1.확률변수와 확률분포\n",
    "    이산확률변수 : 어떤변수 X를 P(X)의 확률로 나오게 할 수 있는. \n",
    "    ex) 주사위 2개를 던졌을때 확률변수 X = {2,3,4,5,6...12}\n",
    "    \n",
    "    이산확률분포 : 이산확률변수의 값에 따라 달라지는 확률들을 전체적으로 정리하여 나열한 것\n",
    "    ex) P(X) = f(X)\n",
    "    P(2) = 1/36 //두개의 합이 2가 나올 확률 f(x)\n",
    "    P(7) = 6/36 //두개의 합이 7이 나올 확률\n",
    "    \n",
    "    주사위의 갯수가 늘어날 수록 종형곡선의 모양에 가까워진다 점점 산모양처럼 됨\n",
    "    \n",
    "    연속확률분포 : 연속적인 값을 가질때 확률 키나,몸무게,온도 등\n",
    "    P(a <= X <= b) = a와b구간의 f(x) 정적분을 \n",
    "    $$ integrate( sqrt(3*x+2), (x,0,1) ) $$\n",
    "  "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
